### ISSUE TITLE
[BUG]Unable to load DFCE archives

### ISSUE THREAD

**Issue by Symon-S** [MrVauxs/vauxs-archives#1]
**Module Version:** v0.4.0

**Describe the bug**
When trying to add an existing DFCE archive, the archive is not created. Might be my naming scheme, but I am uncertain. I have tried naming it a few things in the Title. My DFCE archived files are named like this for example `23_06_19_22.json`

**Browser:Chrome**

**Foundry Version:11.315**

**Game System:PF2e 5.14.4**

**Comment by MrVauxs** [comment]
Apparently `foundry.utils.mergeObject` overrides properties when they are explicitly undefined... Will fix in 0.4.1.
