### ISSUE TITLE
Feature Request: Easy Open Keybind

### ISSUE THREAD

**Issue by Symon-S** [MrVauxs/vauxs-archives#2]
Would be nice if the archive could be easily accessed via a keybind instead of having to open it from the settings menu.
Unless you have something grander planned in a future release.

**Comment by MrVauxs** [comment]
The following is on the todo list:
> Quick Archive - Replace the "Export Chat Log" button with a Vauxs' Archives button.

**Comment by Symon-S** [comment]
Excellent, thanks
