### ISSUE TITLE
[BUG] Only Small Subset of Messages Are Appearing in Archive Viewer When Using DF Chat Enhancement

### ISSUE THREAD

**Issue by Rvby1** [MrVauxs/vauxs-archives#3]
**Module Version:** v0.4.1

**Describe the bug**
When I run an archive on a set of messages, those messages are properly saved out to the JSON file with all of the functionality and meta data they should have. However, when I try to open those archives in the module, I'm not seeing all of the messages. I only see around... maybe 100? It's hard to count for sure--but I know many of my 700~ messages are not being shown.

**To Reproduce**

1. Download the attached log and move it to a location Foundry can access
2. Import the log using Configure Settings > Vauxs' Archives > Open Chat Archives > Add an existing archive
3. Open the archive, called "Test" (or whatever you imported the archive as)
4. Note that only a small subset of the messages appear, and scrolling to the top does not

**Expected behavior**
When you open up an archive and scroll up, it should continue loading more messages from the archive file until it reaches the top of the file

**Browser:**
- Firefox v121.0.1
- Chrome v123.0.6312.58

**Foundry Version:**
v11.315

**Game System:**
D&D 5E 3.03

**Additional context**
I don't get any errors in the console. 

I imagine that it's doing an initial load, but further lazy loading isn't occurring properly for some reason. 

P.S. Thank you for the work on this module! DF's chat archiving never worked for me at all, so this is already a huge improvement. 
[iWq2N4H3MOMKsmN3.json](https://github.com/MrVauxs/vauxs-archives/files/14728566/iWq2N4H3MOMKsmN3.json)

**Comment by MrVauxs** [comment]
Check for any other modules interfering with the module. I cannot replicate this issue.

**Comment by Rvby1** [comment]
Ah, I should have done a quick check without any first. 

It seems like the problem is arising from some sort of conflict with DF Chat Enhancements (or maybe Chat Commander, its dependency). 

I can probably get away without it since Midi QoL can duplicate one of its main benefits (chat coloring), but it might be something to investigate. I also know that DF Chat Enhancements isn't maintained actively anymore, so maybe the compatibility isn't a high priority.

**Comment by MrVauxs** [comment]
It's 100% DF Chat Enhancements, as it has a now-very-outdated feature of limiting the rendering of the chat to 100 messages (Foundry v11 implemented that already).

Get rid of it! You have Karakara's Chat Enhancements for all other features, including chat coloring. https://foundryvtt.com/packages/karakara-chat-enhancements
