### ISSUE TITLE
Missing CSS variables

### ISSUE THREAD

**Issue by morepurplemorebetter** [MrVauxs/vauxs-archives#7]
Thank you very much for fixing bug #6 so quickly!
I'm writing this issue because of the second part of that bug, which I totally understand if it was overlooked.

Looking at the CSS of the headers of the Vauxs' Archives windows (because they have too little padding compared to those of other windows), I see that there are references to CSS variables that don't seem to be set:

* --tjs-app-header-flex
* --tjs-app-header-gap
* --tjs-app-header-padding

![image](https://github.com/MrVauxs/vauxs-archives/assets/8971168/00fcf7af-da3f-4f88-bb39-d9312f14e77d)

As a result of the fallback for the `padding` being different than FoundryVTT's default setting, the button to close windows made by this module look off (see the screenshot in issue #6).

I don't know what those variables are supposed to do, but I would fix this by changing the `padding` to `padding-left` so that at least the top-right buttons don't render differently.

**Comment by MrVauxs** [comment]
I cant say I can replicate this, let alone your styling.
![chrome_pfAeyv2Zk0](https://github.com/MrVauxs/vauxs-archives/assets/32039708/2b20b207-27b9-47b3-a49c-d0e5094983e4)

**Comment by morepurplemorebetter** [comment]
Apologies, I didn't realise that the window styling I was seeing wasn't the FoundryVTT standard. The alternative styling is the result of another module. There is still a 4px padding difference between the default and your module, but that is almost impossible to notice. I'll add some custom CSS to fix the padding.

Do you also not see the missing CSS variables? They probably aren't a big deal, and don't need to be fixed because the fallback values are there.

I see them on a test world, which has only 1 active module. Test world stats:
- FoundryVTT v11.315
- DnD5e v2.4.1
- Vauxs' Archives v1.0.5

**Comment by MrVauxs** [comment]
I have added the variables needed to make it pixel accurate to Foundry defaults.

I cannot promise compatibility with other modules modifying the UI.

![chrome_hxyY9aIwbS](https://github.com/MrVauxs/vauxs-archives/assets/32039708/1d6a75d9-258c-49ff-92c1-518cb0fe2901)

**Comment by morepurplemorebetter** [comment]
Thank you very much!
